version "3.8"

networks:
  backbone:
    external: true

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    networks:
      - backbone
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/etc:/etc/caddy
      - $PWD/config:/config
      - $PWD/data:/data
